FROM java:8
VOLUME /tmp/tomcat
ADD spring-boot-demo-docker-0.0.1-SNAPSHOT.jar springboot-docker.jar
RUN sh -c 'touch /springboot-docker.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/springboot-docker.jar"]